version: '3.3'
services:
    python:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: CNG-Server
        network_mode: host
        image: 'python:latest'
        ports: 
            - '5000:5000'
        volumes:
            - './server:/var/lib/CNG/'